### ISSUE TITLE
error appeared again! Freebsd

### ISSUE THREAD

**Issue by zishucom** [gopherdata/gophernotes#214] opened 2020-07-19 15:56 UTC
i was upgraded the gomacro. and modified the go.mod and go.sum

import(
    "github.com/russross/blackfriday/v2"
)
error writing file "/projects/go/src/github.com/gopherdata/gophernotes/imports/thirdparty/github_com_russross_blackfriday_v2.go": open /projects/go/src/github.com/gopherdata/gophernotes/imports/thirdparty/github_com_russross_blackfriday_v2.go: no such file or directory

**Comment by cosmos72** [comment] 2020-07-20 07:31
We can continue on the old issue #212

**Comment by cosmos72** [comment] 2020-07-20 07:37
Duplicate of #213

**Closed by cosmos72** 2020-07-20 07:37 UTC
Labels: duplicate
